### ISSUE TITLE
REST flavor

### ISSUE THREAD

**Issue by patrickp-at-work** [marmelab/FakeRest#56]
> FakeRest uses a standard REST flavor, described below.

Can you clarify in your docs where this flavor came from? Was it invented by marmelab? Because if it is a common standard also used elsewhere, it would be useful to link it

**Comment by fzaninotto** [comment]
Ah, this flavor was pretty common at the time I wrote the library, because most people I knew did REST that way... But I don't have a spec or a paper to link to. That's the problem of REST: there is no standard. 

The fact that we use the term "standard" in the readme is misleading. It's a common practice.
